const data = [
  {
    id: 1,
    title: "Question 1",
    content: "Describe your job as a color.",
    flipped: false,
  },
  {
    id: 2,
    title: "Question 2",
    content: "If you were a scent, what would you smell like?",
    flipped: false,
  },
  {
    id: 3,
    title: "Question 3",
    content: "Invent a word and its meaning.",
    flipped: false,
  },
  {
    id: 4,
    title: "Question 4",
    content: "If you had a theme song, what would it be?",
    flipped: false,
  },
  {
    id: 5,
    title: "Question 5",
    content: "Design your imaginary dream job title.",
    flipped: false,
  },
  {
    id: 6,
    title: "Question 6",
    content: "Create a motto for your life.",
    flipped: false,
  },
  {
    id: 7,
    title: "Question 7",
    content: "If you were a book, what genre would you be?",
    flipped: false,
  },
  {
    id: 8,
    title: "Question 8",
    content: "Invent a cocktail named after you.",
    flipped: false,
  },
  {
    id: 9,
    title: "Question 9",
    content: "If you were a dessert, what would you be?",
    flipped: false,
  },
  {
    id: 10,
    title: "Question 10",
    content: "Design your personal coat of arms.",
    flipped: false,
  },
  {
    id: 11,
    title: "Question 11",
    content: "If you were a planet, what would your rings be made of?",
    flipped: false,
  },
  {
    id: 12,
    title: "Question 12",
    content: "Create a title for your future autobiography.",
    flipped: false,
  },
  {
    id: 13,
    title: "Question 13",
    content: "If you were a flavor, describe your taste in three words.",
    flipped: false,
  },
  {
    id: 14,
    title: "Question 14",
    content: "Design a flag for your imaginary country.",
    flipped: false,
  },
  {
    id: 15,
    title: "Question 15",
    content: "If you had a magic key, what would it unlock?",
    flipped: false,
  },
  {
    id: 16,
    title: "Question 16",
    content: "If you could paint the sky any color, what would it be?",
    flipped: false,
  },
  {
    id: 17,
    title: "Question 17",
    content: "Design a logo for your personal brand.",
    flipped: false,
  },
  {
    id: 18,
    title: "Question 18",
    content: "If you were a star, what constellation would you belong to?",
    flipped: false,
  },
  {
    id: 19,
    title: "Question 19",
    content: "If your life was a genre of movie, what would it be?",
    flipped: false,
  },
  {
    id: 20,
    title: "Question 20",
    content: "Create a slogan for a product nobody has invented yet.",
    flipped: false,
  },
  {
    id: 21,
    title: "Question 21",
    content: "If your life was a novel, what would be its title?",
    flipped: false,
  },
  {
    id: 22,
    title: "Question 22",
    content: "Design your personal flag. What symbols would it feature?",
    flipped: false,
  },
  {
    id: 23,
    title: "Question 23",
    content: "If you were a plant, what kind would you be and why?",
    flipped: false,
  },
  {
    id: 24,
    title: "Question 24",
    content: "If you could time travel to any artistic era, when and where?",
    flipped: false,
  },
  {
    id: 25,
    title: "Question 25",
    content: "Create a new holiday. How would people celebrate it?",
    flipped: false,
  },
  {
    id: 26,
    title: "Question 26",
    content: "If you could communicate with one species, what would it be?",
    flipped: false,
  },
  {
    id: 27,
    title: "Question 27",
    content:
      "Design a spaceship interior. What futuristic features would it have?",
    flipped: false,
  },
  {
    id: 28,
    title: "Question 28",
    content: "If your life had a fragrance, what would it smell like?",
    flipped: false,
  },
  {
    id: 29,
    title: "Question 29",
    content: "Invent a new word. What does it mean?",
    flipped: false,
  },
  {
    id: 30,
    title: "Question 30",
    content: "Create a title for a book you'll write someday.",
    flipped: false,
  },
];

export { data };
